# Generated by Django 3.0.3 on 2020-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
